# Generated by Django 4.2.5 on 2023-09-21 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("user_pwd", models.CharField(max_length=255)),
                ("user_name", models.CharField(max_length=10)),
                ("user_authority", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "user",
            },
        ),
        migrations.CreateModel(
            name="WishList",
            fields=[
                ("like_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("goods_id", models.BigIntegerField()),
                ("created_at", models.DateTimeField()),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="market.user"
                    ),
                ),
            ],
            options={
                "db_table": "wish_lists",
            },
        ),
        migrations.CreateModel(
            name="Goods",
            fields=[
                ("goods_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(db_index=True, max_length=100)),
                ("status", models.CharField(max_length=10)),
                ("goods_image", models.ImageField(upload_to="goods_images/")),
                ("sell_price", models.IntegerField(null=True)),
                ("view_count", models.IntegerField()),
                ("description", models.TextField()),
                ("refreshed_at", models.DateTimeField(db_index=True)),
                ("created_at", models.DateTimeField()),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="market.user"
                    ),
                ),
            ],
            options={
                "db_table": "goods",
            },
        ),
        migrations.CreateModel(
            name="ChatRoom",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField()),
                (
                    "goods_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="market.goods"
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="market.user"
                    ),
                ),
            ],
            options={
                "db_table": "chat_room",
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                ("chatroom_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("message", models.CharField(max_length=500)),
                ("read_or_not", models.BooleanField()),
                ("created_at", models.DateTimeField()),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="market.user"
                    ),
                ),
            ],
            options={
                "db_table": "chat_messages",
            },
        ),
        migrations.CreateModel(
            name="ActivityArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("distance_meters", models.SmallIntegerField()),
                ("emd_area_ids", models.IntegerField(db_index=True)),
                ("authenticated_at", models.DateTimeField(null=True)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="market.user"
                    ),
                ),
            ],
            options={
                "db_table": "activity_areas",
            },
        ),
    ]
